/**
 * briefDisplayName pin tests (manage-mode plan §4.7 item 2, Design risk 7).
 *
 * Expected strings generated by EXECUTING the ORIGINAL inline expression
 * from app/briefs/briefs-client.tsx:242 (pre-lift):
 *
 *   row.name?.trim() || (topics[0] ? `${capitalize(topics[0])} brief`
 *                                  : "Untitled brief")
 *
 * The lift into lib/brief-display.ts is mechanical; any diff here is a
 * behavior change and must be rejected.
 */
import { describe, it, expect } from "vitest";
import { briefDisplayName } from "@/lib/brief-display";

describe("briefDisplayName — pinned to pre-lift behavior", () => {
  it("non-empty name wins, untrimmed", () => {
    expect(briefDisplayName("Palm oil weekly", ["palm oil"])).toBe("Palm oil weekly");
  });

  it("whitespace-only / empty name falls through to the first topic, capitalized + ' brief'", () => {
    expect(briefDisplayName("  ", ["palm oil"])).toBe("Palm oil brief");
    expect(briefDisplayName("", ["palm oil"])).toBe("Palm oil brief");
    expect(briefDisplayName(null, ["palm oil", "fx"])).toBe("Palm oil brief");
    // Only the first character is uppercased — rest preserved as-is.
    expect(briefDisplayName(null, ["LNG markets"])).toBe("LNG markets brief");
  });

  it("no name, no topics → 'Untitled brief'", () => {
    expect(briefDisplayName(undefined, [])).toBe("Untitled brief");
    expect(briefDisplayName("", [])).toBe("Untitled brief");
  });
});
