/**
 * humanizeSchedule pin tests (exec RC2, manage-mode plan §4.7).
 *
 * Every expected string below was generated by EXECUTING the ORIGINAL
 * module-private implementation (app/briefs/briefs-client.tsx:533 /
 * app/briefs/[id]/brief-detail-client.tsx:794, pre-lift) against these
 * fixtures, BEFORE the function was lifted into lib/schedule.ts. The lift
 * is verbatim — any diff here is a behavior change and must be rejected.
 *
 * Covers the tzLabel rendering (briefs-client.tsx:541–542 pre-lift), every
 * cadence kind, the weekdays edge cases, and the defensive fallbacks.
 */
import { describe, it, expect } from "vitest";
import { humanizeSchedule, saveTransitionMessage } from "@/lib/schedule";

describe("humanizeSchedule — pinned to pre-lift behavior", () => {
  it("non-object / missing cadence → 'Schedule not set'", () => {
    expect(humanizeSchedule(null)).toBe("Schedule not set");
    expect(humanizeSchedule(undefined)).toBe("Schedule not set");
    expect(humanizeSchedule("string")).toBe("Schedule not set");
    expect(humanizeSchedule({})).toBe("Schedule not set");
    expect(
      humanizeSchedule({ timeLocal: "07:00", timezone: "Asia/Kuala_Lumpur" })
    ).toBe("Schedule not set");
    expect(humanizeSchedule({ cadence: { kind: "bogus" }, timeLocal: "07:00" })).toBe(
      "Schedule not set"
    );
  });

  it("daily — default weekdays, full week, tzLabel rendering", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "daily" },
        timeLocal: "07:00",
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe("Daily at 07:00 (Asia/Kuala_Lumpur)");
    expect(
      humanizeSchedule({
        cadence: { kind: "daily", weekdays: [1, 2, 3, 4, 5, 6, 7] },
        timeLocal: "08:30",
      })
    ).toBe("Daily at 08:30");
  });

  it("daily — Mon–Fri collapses to 'Weekdays'", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "daily", weekdays: [1, 2, 3, 4, 5] },
        timeLocal: "07:00",
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe("Weekdays at 07:00 (Asia/Kuala_Lumpur)");
  });

  it("daily — arbitrary weekday subsets list day names", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "daily", weekdays: [2, 4, 6] },
        timeLocal: "09:15",
        timezone: "UTC",
      })
    ).toBe("Tue, Thu, Sat at 09:15 (UTC)");
    // 5 days that are NOT Mon–Fri must NOT collapse to "Weekdays".
    expect(
      humanizeSchedule({
        cadence: { kind: "daily", weekdays: [1, 3, 4, 5, 6] },
        timeLocal: "07:00",
      })
    ).toBe("Mon, Wed, Thu, Fri, Sat at 07:00");
  });

  it("weekly — middle-dot separator, empty-weekdays quirk preserved", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "weekly", weekdays: [1] },
        timeLocal: "07:00",
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe("Weekly · Mon at 07:00 (Asia/Kuala_Lumpur)");
    expect(
      humanizeSchedule({
        cadence: { kind: "weekly", weekdays: [5, 7] },
        timeLocal: "18:00",
      })
    ).toBe("Weekly · Fri, Sun at 18:00");
    // Pre-lift quirk, deliberately preserved (verbatim move): no weekdays
    // renders a double space.
    expect(
      humanizeSchedule({ cadence: { kind: "weekly" }, timeLocal: "18:00" })
    ).toBe("Weekly ·  at 18:00");
  });

  it("monthly — numeric day and 'last'", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "monthly", monthlyDay: 1 },
        timeLocal: "07:00",
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe("Monthly on day 1 at 07:00 (Asia/Kuala_Lumpur)");
    expect(
      humanizeSchedule({
        cadence: { kind: "monthly", monthlyDay: "last" },
        timeLocal: "23:00",
      })
    ).toBe("Monthly on last day at 23:00");
  });

  it("custom_cron — raw expression + tzLabel", () => {
    expect(
      humanizeSchedule({
        cadence: { kind: "custom_cron", cronExpr: "0 7 * * 1" },
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe("Custom: 0 7 * * 1 (Asia/Kuala_Lumpur)");
  });

  it("missing timeLocal quirk preserved (trailing 'at ')", () => {
    expect(humanizeSchedule({ cadence: { kind: "daily" } })).toBe("Daily at ");
  });
});

/**
 * saveTransitionMessage — the deterministic post-save transition bubble
 * (manage-mode plan §3.1 item 1; appended in the same file because it is
 * humanizeSchedule's sibling: same time/timezone sources, exec advisory 6).
 * Copy is final-candidate per COPY_GUIDE §4 — computed time, never a
 * hard-coded clock string.
 */
describe("saveTransitionMessage — §3.1 transition copy", () => {
  it("time + timezone → full computed sentence", () => {
    expect(
      saveTransitionMessage({
        timeLocal: "07:00",
        timezone: "Asia/Kuala_Lumpur",
      })
    ).toBe(
      "Saved. Your first brief arrives tomorrow at 07:00 (Asia/Kuala_Lumpur)."
    );
  });

  it("time without timezone → no empty parens", () => {
    expect(saveTransitionMessage({ timeLocal: "08:30", timezone: null })).toBe(
      "Saved. Your first brief arrives tomorrow at 08:30."
    );
    expect(saveTransitionMessage({ timeLocal: "08:30", timezone: "  " })).toBe(
      "Saved. Your first brief arrives tomorrow at 08:30."
    );
  });

  it("no known time → COPY_GUIDE fallback 'tomorrow morning'", () => {
    expect(saveTransitionMessage({})).toBe(
      "Saved. Your first brief arrives tomorrow morning."
    );
    expect(saveTransitionMessage({ timeLocal: "  ", timezone: "Asia/Kuala_Lumpur" })).toBe(
      "Saved. Your first brief arrives tomorrow morning."
    );
  });
});
